Update patch set 1
Patch Set 1:

(1 comment)

Hi Steven,

I am running Functest against our commercial product which currently only supports v2.0. Domains seem to be a v3 feature (missing from [1], available in [2]), the test fails as follows:

======================================================================                                          
ERROR: test_create_project_minimal (snaps.openstack.utils.tests.keystone_utils_tests.KeystoneUtilsTests)
----------------------------------------------------------------------                                   
Traceback (most recent call last):                                                         
  File "/usr/lib/python2.7/site-packages/snaps/openstack/utils/tests/keystone_utils_tests.py", line 126, in test_create_project_minimal
    self.keystone, project.domain_id)                                                                         
  File "/usr/lib/python2.7/site-packages/snaps/openstack/utils/keystone_utils.py", line 377, in get_domain_by_id
    domain = keystone.domains.get(domain_id)                                                             
  File "/usr/lib/python2.7/site-packages/keystoneclient/httpclient.py", line 894, in __getattr__
    raise AttributeError(_("Unknown Attribute: %s") % name)                                                                              
AttributeError: Unknown Attribute: domains

[1] https://developer.openstack.org/api-ref/identity/v2/
[2] https://developer.openstack.org/api-ref/identity/v3/#domains

Patch-set: 1
Label: Verified=0