reduce instance's memory size
when using snaps to test small OpenStack env(devstack or all-in-one),
testcase  will fail due to not enough memory for a vm. As a
basic test using cirros, only allocating ip and test the connectivity is
needed, 128M should be enough.
the error msg is:

  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py",
  line 80, in request
      raise exceptions.from_response(resp, body, url, method)
	ClientException: Unknown Error (HTTP 504)

Change-Id: Ibfb27018ffd25292bcf80f69e8cb205b2c9c334b
Signed-off-by: SerenaFeng <feng.xiaowei@zte.com.cn>