Update patch set 1
Patch Set 1: Code-Review-1

(1 comment)

All tests are passing except ansible_utils_tests.py due to:
Exception: global name 'OpenStackImage' is not defined

Patch-set: 1
Label: Code-Review=-1